---
- name: Install various tools using apt package manager
  gather_facts: True
  hosts: all
  vars: 
    tools_dir: "/home/ubuntu/tools"

  tasks:
    - name: Create Tools Directory
      file:
        state: directory
        path: "{{ tools_dir }}"
        mode: 0755

    - name: Install a list of tools through apt
      become: true
      apt:
        pkg:
        - nmap
        - sqlmap
        - net-tools
        - unzip
  
    - name: Install Multiple Python Tools from Pip3
      pip:
        name:
          - semgrep
          - awscli
          - docker-py
        executable: pip3

# Please check link https://apt.metasploit.com/ for newer images or if 404 errors.
    - name: Install Metasploit
      become: true
      apt:
        deb: https://apt.metasploit.com/pool/main/m/metasploit-framework/metasploit-framework_6.4.17~20240709102842~1rapid7-1_amd64.deb
        install_recommends: true
      ignore_errors: true

    - name: Install Nuclei
      include_tasks: nuclei.yml
      
    - name: Download kubectl
      get_url:
        url: https://dl.k8s.io/release/v1.24.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'
      become: true

    - name: Download Opa
      get_url:
        url: https://github.com/open-policy-agent/opa/releases/download/v0.57.0/opa_linux_amd64
        dest: /usr/local/bin/opa
        mode: '0755'
      become: true

    - name: Download mdbook
      unarchive:
        src: https://github.com/rust-lang/mdBook/releases/download/v0.4.35/mdbook-v0.4.35-x86_64-unknown-linux-gnu.tar.gz
        dest: /usr/local/bin/
        remote_src: yes
        mode: '0755'
      become: true

    - name: Download BFG Jar
      get_url:
        url: https://repo1.maven.org/maven2/com/madgag/bfg/1.14.0/bfg-1.14.0.jar
        dest: "{{ tools_dir }}/bfg.jar"
        mode: '0755'

    - name: Download Terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.4.0/terraform_1.4.0_linux_amd64.zip
        dest: /usr/local/bin/
        remote_src: yes
        mode: '0755'
      become: true
