---
- name: Install Nginx and configure it.
  gather_facts: True
  hosts: all
  vars: 
    hostname: "{{ hostname }}"
    email: "{{ email }}"
    
  tasks:
    - name: Install Nginx
      become: yes    
      apt:
        name: nginx
        state: latest

# https://rolflekang.com/using-certbot-with-ansible 
    - name: Install Multiple Python Tools from Pip3
      become: yes
      pip:
        name:
          - certbot
          - certbot-nginx
        executable: pip3

    - name: Register certbot
      become: yes    
      shell: |
        certbot -n register --agree-tos --email {{ email }}
        touch /etc/letsencrypt/.registered
      args:
        creates: /etc/letsencrypt/.registered

    - name: Setup cronjob for renewal
      become: yes
      cron:
        name: certbot-renewal
        job: "/bin/bash -lc '/usr/local/bin/certbot -q renew'"
        minute: "0"
        hour: "14"

    - name: 'Get certificate'
      become: yes
      command: '/usr/local/bin/certbot --nginx certonly -d {{ hostname }}'
      args:
        creates: '/etc/letsencrypt/live/{{ hostname }}'

    - name: Write nginx default conf file
      become: yes
      template:
        src: default.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        owner: root
        group: root
        mode: a+rx
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      become: yes
      service:
        name: nginx
        state: restarted
        enabled: true
     