---
- name: Installs all languages generally needed
  gather_facts: true
  hosts: all
  become: true
  vars:
      home_dir: "/home/ubuntu"  

  tasks:
  - name: Install a list of languages through apt
    become: true
    apt:
      pkg:
      - default-jdk
      - nodejs
      - python3-pip
      - npm
      - zsh

  - name: Install GoLang
    include_tasks: golang.yml