---
- name: Install code-server
  gather_facts: True
  hosts: all
  vars: 
    code_server_bin_dir: "/usr/local/bin"
    code_server_data_dir: "/home/ubuntu/code-server"
    code_server_dir: "/opt/code-server"
    code_server_password: "{{ password }}"
    code_server_user: ubuntu
    code_server_version: 4.10.1
    code_server_tar_url: "https://github.com/coder/code-server/releases/download/v{{ code_server_version }}/code-server-{{ code_server_version }}-linux-amd64.tar.gz"
    code_server_port: 8080
    code_server_service_dir: /lib/systemd/system/code-server.service

  tasks:
    - name: Create Code-Server Directory
      become: yes
      file:
        state: directory
        path: "{{ code_server_dir }}"
        mode: 0755

    - name: Create Code-Server Data Directory
      become: yes
      file:
        state: directory
        path: "{{ code_server_data_dir }}"
        owner: "{{ code_server_user }}"
        group: "{{ code_server_user }}"
        mode: 0755

    - name: Download code-server tar file
      become: yes
      unarchive:
        remote_src: yes
        src: "{{ code_server_tar_url }}"
        dest: "{{ code_server_dir }}"
        extra_opts:
          - --strip-components=1

    - name: ln -s /opt/code-server/code-server /usr/local/bin/code-server
      become: yes
      file:
        state: link
        src: "{{ code_server_dir }}//bin/code-server"
        dest: "{{ code_server_bin_dir }}/code-server"
        force: yes
      notify: Restart code-server

    - name: Copy code-server configuration file
      become: yes
      template:
        src: config.yaml.j2
        dest: "{{ code_server_data_dir }}/config.yaml"
        mode: 0644

    - name: Copy code-server systemd unit file
      become: yes
      template:
        src: code-server.service.j2
        dest: "{{ code_server_service_dir }}"
        mode: 0644

    - name: Enable code-server service
      become: yes
      systemd:
        name: code-server
        enabled: yes

    - name: Start code-server
      become: yes
      systemd:
        state: started
        name: code-server

    - name: Wait for Code Server to start
      wait_for:
        port: "{{ code_server_port }}"
        timeout: 15

  handlers:
    - name: Restart code-server
      become: yes
      systemd:
        daemon-reload: yes
        name: code-server
        state: restarted
        no_block: yes     